/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mop' at '23.12.16 17:49' with Gradle 3.0
 *
 * @author mop, @date 23.12.16 17:49
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
