import org.junit.Test;
import org.junit.Before;

import com.arangodb.ArangoDB;
import com.arangodb.ArangoCollection;
import com.arangodb.entity.BaseDocument;
import com.arangodb.entity.CollectionEntity;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'mop' at '23.12.16 17:49' with Gradle 3.0
 *
 * @author mop, @date 23.12.16 17:49
 */
public class ArangoDbTest {
	private ArangoDB arangoDB;

	@Before
	public void setUp() {
		arangoDB = new ArangoDB.Builder().build();
		arangoDB.db("_system").createCollection("test");
	}
	
    @Test
    public void testReadWrite() {
    	ArangoCollection collection = arangoDB.db("_system").collection("test");
    	for (int i=0;i<100000;i++) {
			BaseDocument document = new BaseDocument();
			document.setKey("key" + i);
	    	document.addAttribute("test", "piffzpaffz");
			collection.insertDocument(document);
		}
    	for (int i=0;i<100000;i++) {
			collection.getDocument("key_" + i, BaseDocument.class);
		}
    }
}
